import { useMemo, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import './App.css'

type Status = 'درخواست پرونده' | 'پرونده پرسنلی' | 'کارت عادی' | 'سه‌برگی عادی' | 'تکمیل اطلاعات' | 'پرونده فعال' | 'ارسال به مرکز' | 'بررسی مرکز' | 'تأیید شده' | 'رد شده' | 'ارسال به شرکت' | 'پایان کار'
type Page = 'dashboard' | 'persons' | 'workflow' | 'activities' | 'users' | 'reports' | 'settings'
type Permission = 'view_persons' | 'create_person' | 'change_status' | 'view_activities' | 'manage_users' | 'view_reports'
type Person = { id:string; firstName:string; lastName:string; nationalId:string; birthDate:string; fatherName:string; status:Status; updatedAt:string; updatedBy:string }
type Activity = { id:string; personId:string; personName:string; action:string; previousStatus:Status|null; newStatus:Status|null; rejectionReason:string|null; createdAt:string; createdBy:string; createdByUserId:string }
type Audit = { id:string; action:string; target:string; createdAt:string; createdBy:string }

const workflow:Status[]=['درخواست پرونده','پرونده پرسنلی','کارت عادی','سه‌برگی عادی','تکمیل اطلاعات','پرونده فعال','ارسال به مرکز','بررسی مرکز','تأیید شده','رد شده','ارسال به شرکت','پایان کار']
const nextStatuses:Partial<Record<Status,Status[]>>={
  'درخواست پرونده':['پرونده پرسنلی'],'پرونده پرسنلی':['کارت عادی'],'کارت عادی':['سه‌برگی عادی'],'سه‌برگی عادی':['تکمیل اطلاعات'],
  'تکمیل اطلاعات':['پرونده فعال'],'پرونده فعال':['ارسال به مرکز'],'ارسال به مرکز':['بررسی مرکز'],
  'بررسی مرکز':['تأیید شده','رد شده'],'تأیید شده':['ارسال به شرکت'],'رد شده':['تکمیل اطلاعات'],'ارسال به شرکت':['پایان کار'],
}
const tones:Record<Status,string>={'درخواست پرونده':'blue','پرونده پرسنلی':'indigo','کارت عادی':'purple','سه‌برگی عادی':'purple','تکمیل اطلاعات':'amber','پرونده فعال':'green','ارسال به مرکز':'cyan','بررسی مرکز':'orange','تأیید شده':'green','رد شده':'red','ارسال به شرکت':'pink','پایان کار':'slate'}
const seedNames=[['علی','رضایی','محمد'],['سارا','احمدی','حسن'],['محمد','کریمی','علی'],['نگار','موسوی','رضا'],['امیر','حسینی','کاظم'],['مریم','اکبری','جواد'],['رضا','مرادی','احمد'],['نیلوفر','قاسمی','حسین'],['مهدی','صادقی','علی'],['پریسا','یوسفی','محمود'],['حامد','نوری','حسن'],['الهام','شریفی','رضا'],['سینا','طاهری','کریم'],['فاطمه','نعمتی','محمد'],['یاسر','رستمی','اکبر'],['مهسا','کاظمی','حسین'],['آرمان','مهدوی','رضا'],['سمیه','رحیمی','علی'],['نوید','حیدری','مسعود'],['آتنا','جعفری','حسن']] as const
const initialPeople:Person[]=seedNames.map(([firstName,lastName,fatherName],i)=>({id:`P-${14001+i}`,firstName,lastName,fatherName,nationalId:`0012345${String(i).padStart(3,'0')}`,birthDate:`۱۳۷${i%10}/${String(i%12+1).padStart(2,'0')}/${String(i%27+1).padStart(2,'0')}`,status:workflow[i%workflow.length],updatedAt:`${i+1} شهریور ۱۴۰۵`,updatedBy:i%2?'مریم رضایی':'احمد محمدی'}))
const rolePermissions:Record<string,Permission[]>={admin:['view_persons','create_person','change_status','view_activities','manage_users','view_reports'],assistant:['view_persons','create_person'],reviewer:['view_persons','change_status','view_activities']}
const normalizeId=(value:string)=>value.trim().replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d)))
const validNationalId=(value:string)=>{if(!/^\d{10}$/.test(value)||/^(\d)\1{9}$/.test(value))return false;const sum=value.slice(0,9).split('').reduce((n,d,i)=>n+Number(d)*(10-i),0)%11;const check=Number(value[9]);return check===(sum<2?sum:11-sum)}
const validBirthDate=(value:string)=>/^(13|14)\d{2}\/(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])$/.test(value)&&value<='1405/06/12'

function Icon({name}:{name:string}){const p:Record<string,string>={grid:'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-3.87',workflow:'M4 4h6v6H4zM14 14h6v6h-6zM10 7h4a2 2 0 0 1 2 2v5',activity:'M3 12h4l3-8 4 16 3-8h4',shield:'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10ZM9 12l2 2 4-4',settings:'M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6M19 15l2 2-2 2-2-2',search:'M11 18a7 7 0 1 0 0-14 7 7 0 0 0 0 14ZM20 20l-4-4',bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9',plus:'M12 5v14M5 12h14',close:'M6 6l12 12M18 6 6 18',check:'m5 12 4 4L19 6'};return <svg viewBox="0 0 24 24"><path d={p[name]??p.grid}/></svg>}
function Avatar({text,tone='blue'}:{text:string;tone?:string}){return <span className={`avatar ${tone}`}>{text}</span>}
function Badge({status}:{status:Status}){return <span className={`badge ${tones[status]}`}><i/>{status}</span>}
function Heading({title,subtitle,action}:{title:string;subtitle:string;action?:ReactNode}){return <div className="heading"><div><small>سامانه ناب</small><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>}

export default function App(){
  const [authenticated,setAuthenticated]=useState(false),[role,setRole]=useState('admin'),[page,setPage]=useState<Page>('dashboard'),[people,setPeople]=useState(initialPeople),[query,setQuery]=useState(''),[filter,setFilter]=useState('همه وضعیت‌ها'),[selected,setSelected]=useState<Person|null>(null),[createOpen,setCreateOpen]=useState(false),[toast,setToast]=useState('')
  const [activities,setActivities]=useState<Activity[]>(initialPeople.map((p,i)=>({id:`ACT-${i}`,personId:p.id,personName:`${p.firstName} ${p.lastName}`,action:i%2?'ایجاد پرونده جدید':'تغییر وضعیت پرونده',previousStatus:null,newStatus:p.status,rejectionReason:p.status==='رد شده'?'نقص اطلاعات':null,createdAt:`${p.updatedAt} · ۱۴:۳۲`,createdBy:p.updatedBy,createdByUserId:p.updatedBy==='احمد محمدی'?'admin':'assistant'})))
  const [audit,setAudit]=useState<Audit[]>([{id:'AUD-1',action:'ورود به سامانه',target:'admin',createdAt:'امروز · ۰۸:۴۵',createdBy:'احمد محمدی'}])
  const can=(permission:Permission)=>rolePermissions[role].includes(permission)
  const filtered=useMemo(()=>people.filter(p=>(!query||`${p.firstName} ${p.lastName} ${p.nationalId}`.includes(query))&&(filter==='همه وضعیت‌ها'||p.status===filter)),[people,query,filter])
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),2400)}
  const updateStatus=(person:Person,next:Status,reason:string|null)=>{const now='امروز · ۱۴:۳۲';setPeople(current=>current.map(p=>p.id===person.id?{...p,status:next,updatedAt:now,updatedBy:'احمد محمدی'}:p));setActivities(current=>[{id:`ACT-${Date.now()}`,personId:person.id,personName:`${person.firstName} ${person.lastName}`,action:next==='رد شده'?'رد پرونده':'تغییر وضعیت پرونده',previousStatus:person.status,newStatus:next,rejectionReason:reason,createdAt:now,createdBy:'احمد محمدی',createdByUserId:'admin'},...current]);setAudit(current=>[{id:`AUD-${Date.now()}`,action:next==='رد شده'?'رد پرونده':'تغییر وضعیت پرونده',target:`${person.firstName} ${person.lastName}`,createdAt:now,createdBy:'احمد محمدی'},...current]);setSelected(null);notify('وضعیت و تاریخچه پرونده ثبت شد')}
  if(!authenticated)return <Login onLogin={(nextRole)=>{setRole(nextRole);setAuthenticated(true)}}/>
  const nav:[Page,string,string][]=[['dashboard','داشبورد','grid'],['persons','مدیریت افراد','users'],['workflow','گردش‌کار پرونده','workflow'],['activities','گزارش فعالیت‌ها','activity'],['users','کاربران و دسترسی‌ها','shield'],['reports','گزارش‌ها و Audit Log','activity'],['settings','تنظیمات','settings']]
  return <div className="app" dir="rtl"><aside className="sidebar"><div className="brand"><b>ن</b><span><strong>ناب</strong><small>سامانه مدیریت پرونده</small></span></div><small className="menu-title">منوی اصلی</small>{nav.filter(([id])=>id==='dashboard'||id==='persons'||(id==='workflow'&&can('change_status'))||(id==='activities'&&can('view_activities'))||(id==='users'&&can('manage_users'))||(id==='reports'&&can('view_reports'))||id==='settings').map(([id,label,icon])=><button className={`nav ${page===id?'active':''}`} key={id} onClick={()=>setPage(id)}><Icon name={icon}/><span>{label}</span>{id==='activities'&&<em>۳</em>}</button>)}<div className="side-bottom"><div className="help">؟<span>نیاز به راهنمایی دارید؟<small>راهنمای سامانه را ببینید</small></span></div><button className="profile" onClick={()=>setAuthenticated(false)}><Avatar text="ا" tone="green"/><span><b>احمد محمدی</b><small>مدیر سیستم · خروج</small></span></button></div></aside><main><header><span>خانه / <b>{nav.find(item=>item[0]===page)?.[1]}</b></span><div className="head-user"><button><Icon name="bell"/></button><Avatar text="ا" tone="green"/><span><b>احمد محمدی</b><small>{role==='admin'?'مدیر سیستم':role==='assistant'?'دستیار':'کارشناس مرکز'}</small></span></div></header><div className="content">{page==='dashboard'&&<Dashboard people={people} onPersons={()=>setPage('persons')} onSelect={setSelected}/>} {page==='persons'&&<Persons people={filtered} query={query} filter={filter} setQuery={setQuery} setFilter={setFilter} canCreate={can('create_person')} onCreate={()=>setCreateOpen(true)} onSelect={setSelected}/>} {page==='workflow'&&<WorkflowBoard people={people} canChange={can('change_status')} onSelect={setSelected}/>} {page==='activities'&&<Activities activities={activities}/>} {page==='users'&&<Users/>} {page==='reports'&&<Reports activities={activities} audit={audit}/>} {page==='settings'&&<Settings/>}</div></main>{selected&&<PersonModal person={selected} canChange={can('change_status')} onClose={()=>setSelected(null)} onUpdate={updateStatus}/>} {createOpen&&can('create_person')&&<CreateModal existing={people} onClose={()=>setCreateOpen(false)} onCreate={p=>{setPeople(current=>[p,...current]);setActivities(current=>[{id:`ACT-${Date.now()}`,personId:p.id,personName:`${p.firstName} ${p.lastName}`,action:'ایجاد پرونده جدید',previousStatus:null,newStatus:p.status,rejectionReason:null,createdAt:'همین الان',createdBy:'احمد محمدی',createdByUserId:'admin'},...current]);setAudit(current=>[{id:`AUD-${Date.now()}`,action:'ایجاد فرد',target:`${p.firstName} ${p.lastName}`,createdAt:'همین الان',createdBy:'احمد محمدی'},...current]);setCreateOpen(false);notify('فرد جدید با موفقیت ثبت شد')}}/>}{toast&&<div className="toast">✓ {toast}</div>}</div>
}

function Login({onLogin}:{onLogin:(role:string)=>void}){const [username,setUsername]=useState('admin'),[password,setPassword]=useState('admin'),[error,setError]=useState(''),[loading,setLoading]=useState(false);return <div className="login" dir="rtl"><section><div className="login-brand">ن</div><h1>مدیریت هوشمند<br/><i>پرونده‌های سازمانی</i></h1><p>همه‌چیز برای مدیریت دقیق، امن و شفاف در یک سامانه.</p><span>✓ دسترسی امن و سطح‌بندی شده</span><span>✓ گزارش‌گیری لحظه‌ای</span></section><form onSubmit={(e:FormEvent)=>{e.preventDefault();if(!username||!password){setError('نام کاربری و رمز عبور الزامی است.');return}setLoading(true);setTimeout(()=>{setLoading(false);if(username==='admin'&&password==='admin')onLogin('admin');else if(username==='assistant'&&password==='assistant')onLogin('assistant');else if(username==='reviewer'&&password==='reviewer')onLogin('reviewer');else setError('نام کاربری یا رمز عبور نادرست است.')},400)}}><div className="form-brand">ن <b>خوش آمدید</b><small>برای ورود به سامانه وارد شوید</small></div><label>نام کاربری<input value={username} onChange={e=>{setUsername(e.target.value);setError('')}}/></label><label>رمز عبور<input type="password" value={password} onChange={e=>{setPassword(e.target.value);setError('')}}/></label>{error&&<div className="error">{error}</div>}<div className="login-row"><span>□ مرا به خاطر بسپار</span><a>رمز عبور را فراموش کرده‌اید؟</a></div><button className="primary" disabled={loading}>{loading?'در حال بررسی...':'ورود به سامانه ←'}</button><small className="demo">admin/admin · assistant/assistant · reviewer/reviewer</small></form></div>}

function Dashboard({people,onPersons,onSelect}:{people:Person[];onPersons:()=>void;onSelect:(p:Person)=>void}){const count=(s:Status)=>people.filter(p=>p.status===s).length;return <><Heading title="صبح بخیر، احمد 👋" subtitle="در یک نگاه وضعیت پرونده‌ها و فعالیت‌های سامانه را بررسی کنید." action={<button className="primary" onClick={onPersons}><Icon name="plus"/> ثبت فرد جدید</button>}/><div className="stats">{[['کل افراد',people.length,'blue'],['درخواست‌های جدید',count('درخواست پرونده'),'amber'],['پرونده‌های فعال',count('پرونده فعال'),'green'],['در انتظار بررسی',count('بررسی مرکز'),'purple']].map(([label,value,color])=><div className="stat" key={String(label)}><div className={`stat-icon ${color}`}><Icon name="users"/></div><span>{label}<b>{Number(value).toLocaleString('fa-IR')}</b><small>در سامانه ثبت شده</small></span></div>)}</div><div className="grid2"><section className="panel"><h2>روند پرونده‌ها <small>تعداد پرونده‌های ثبت‌شده در ۶ ماه گذشته</small></h2><div className="chart"><svg viewBox="0 0 600 180" preserveAspectRatio="none"><path d="M0 140 C60 140 80 100 140 125 S210 130 260 90 S330 110 380 80 S440 60 490 72 S540 50 600 18 V180H0Z" fill="#e8ecff"/><path d="M0 140 C60 140 80 100 140 125 S210 130 260 90 S330 110 380 80 S440 60 490 72 S540 50 600 18" fill="none" stroke="#5267f5" strokeWidth="3"/></svg><div>فروردین - اردیبهشت - خرداد - تیر - مرداد - شهریور</div></div></section><section className="panel"><h2>وضعیت پرونده‌ها <small>بر اساس مرحله‌ی گردش‌کار</small></h2><div className="donut"><div><b>{people.length}</b><small>کل پرونده</small></div></div><div className="legend">● فعال {count('پرونده فعال')}<br/>● در انتظار بررسی {count('بررسی مرکز')}<br/>● رد شده {count('رد شده')}<br/>● پایان یافته {count('پایان کار')}</div></section></div><div className="grid2"><section className="panel"><div className="panel-title"><h2>آخرین افراد ثبت‌شده</h2><button onClick={onPersons}>مشاهده همه ←</button></div>{people.slice(0,6).map(p=><div className="mini-row" key={p.id} onClick={()=>onSelect(p)}><span><Avatar text={p.firstName[0]}/><b>{p.firstName} {p.lastName}<small>{p.id}</small></b></span><Badge status={p.status}/><small>{p.updatedAt}</small></div>)}</section><section className="panel"><div className="panel-title"><h2>فعالیت‌های اخیر</h2></div>{people.slice(0,5).map((p,i)=><div className="activity" key={p.id}><i className={`dot d${i}`}/><span><b>{i%2?'ایجاد پرونده جدید':'تغییر وضعیت پرونده'}</b><small>{p.firstName} {p.lastName} · {p.status}</small></span><time>امروز، ۱۴:۳۲</time></div>)}</section></div></>}

function Persons({people,query,filter,setQuery,setFilter,canCreate,onCreate,onSelect}:{people:Person[];query:string;filter:string;setQuery:(v:string)=>void;setFilter:(v:string)=>void;canCreate:boolean;onCreate:()=>void;onSelect:(p:Person)=>void}){return <><Heading title="افراد" subtitle="اطلاعات افراد و وضعیت پرونده‌های آن‌ها را مدیریت کنید." action={canCreate?<button className="primary" onClick={onCreate}><Icon name="plus"/> افزودن فرد</button>:undefined}/><section className="panel people"><div className="toolbar"><div className="search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جست‌وجو بر اساس نام، نام خانوادگی یا کد ملی..."/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>همه وضعیت‌ها</option>{workflow.map(s=><option key={s}>{s}</option>)}</select></div><div className="people-head">فرد | کد ملی | تاریخ تولد | وضعیت پرونده | آخرین فعالیت | ثبت‌کننده</div>{people.map(p=><div className="person-row" key={p.id} onClick={()=>onSelect(p)}><span><Avatar text={p.firstName[0]}/><b>{p.firstName} {p.lastName}<small>{p.id}</small></b></span><span>{p.nationalId}</span><span>{p.birthDate}</span><Badge status={p.status}/><span>{p.updatedAt}</span><span>{p.updatedBy}</span></div>)}{!people.length&&<div className="empty">نتیجه‌ای پیدا نشد</div>}</section></>}

function WorkflowBoard({people,canChange,onSelect}:{people:Person[];canChange:boolean;onSelect:(p:Person)=>void}){return <><Heading title="گردش‌کار پرونده" subtitle="پرونده‌ها را در مسیر مرحله‌ای ثبت تا پایان کار دنبال کنید."/><div className="workflow">{workflow.slice(0,9).map((status,i)=><section key={status}><h3><b>{i+1}</b>{status}<small>{people.filter(p=>p.status===status).length} پرونده</small></h3>{people.filter(p=>p.status===status).map(p=><button disabled={!canChange} key={p.id} onClick={()=>onSelect(p)}><Avatar text={p.firstName[0]}/><span><b>{p.firstName} {p.lastName}</b><small>{p.id}</small></span></button>)}</section>)}</div></>}
function Activities({activities}:{activities:Activity[]}){return <><Heading title="گزارش فعالیت‌ها" subtitle="Activity Log تاریخچه‌ی دائمی تغییرات پرونده‌هاست و قابل حذف نیست." action={<button className="outline">خروجی اکسل ←</button>}/><section className="panel activity-table">{activities.map(a=><div className="activity-row" key={a.id}><i className="dot d1"/><span><b>{a.action}</b><small>{a.personName}{a.rejectionReason?` · علت رد: ${a.rejectionReason}`:''}</small></span>{a.newStatus&&<Badge status={a.newStatus}/>}<time>{a.createdAt}</time><em>{a.createdBy}</em></div>)}</section></>}
function Users(){return <><Heading title="کاربران و دسترسی‌ها" subtitle="مدیریت کاربران و Permission-Based Access Control." action={<button className="primary"><Icon name="plus"/> کاربر جدید</button>}/><section className="panel users">{[['احمد محمدی','مدیر سیستم','دسترسی کامل','green'],['مریم رضایی','کارشناس پرونده','مدیریت افراد','blue'],['محمد رضایی','کارشناس مرکز','بررسی پرونده','purple'],['سارا کریمی','اپراتور','مشاهده گزارش‌ها','orange']].map(u=><div className="user" key={u[0]}><Avatar text={u[0][0]} tone={u[3]}/><span><b>{u[0]}</b><small>{u[1]}</small><em>● {u[2]}</em></span><button>•••</button></div>)}</section><section className="panel permission-panel"><h2>مجوزهای نمونه دستیار</h2><p>دستیار فقط به عملیات مجاز پرونده دسترسی دارد.</p><div className="permission-list"><span>✓ مشاهده افراد</span><span>✓ ایجاد فرد</span><span className="disabled">× حذف فرد</span><span className="disabled">× تغییر Permission</span></div></section></>}
function Reports({activities,audit}:{activities:Activity[];audit:Audit[]}){return <><Heading title="گزارش‌ها و Audit Log" subtitle="گزارش‌های مدیریتی و عملیات حساس ثبت‌شده در سامانه." action={<button className="outline">خروجی گزارش ←</button>}/><div className="stats"><div className="stat"><span>کل Activityها<b>{activities.length}</b><small>رویداد پرونده</small></span></div><div className="stat"><span>Audit Log<b>{audit.length}</b><small>عملیات حساس</small></span></div><div className="stat"><span>پرونده‌های رد شده<b>{activities.filter(a=>a.newStatus==='رد شده').length}</b><small>نیازمند اصلاح</small></span></div><div className="stat"><span>ثبت امروز<b>۲۴</b><small>عملیات ثبت‌شده</small></span></div></div><div className="grid2"><section className="panel"><h2>Audit Log <small>رویدادهای حساس و غیرقابل حذف</small></h2>{audit.map(a=><div className="audit-row" key={a.id}><span><b>{a.action}</b><small>هدف: {a.target}</small></span><time>{a.createdAt}<br/>{a.createdBy}</time></div>)}</section><section className="panel"><h2>خلاصه‌ی وضعیت‌ها</h2><div className="report-bars">{workflow.slice(0,8).map((s,i)=><div key={s}><span>{s}<b>{18-i*2}</b></span><i><em style={{width:`${100-i*9}%`}}/></i></div>)}</div></section></div></>}
function Settings(){return <><Heading title="تنظیمات" subtitle="تنظیمات عمومی و امنیتی سامانه ناب."/><div className="grid2"><section className="panel settings"><h2>تنظیمات عمومی</h2><p>اطلاعات پایه سامانه</p><label>نام سامانه<input defaultValue="سامانه مدیریت پرونده ناب"/></label><label>منطقه زمانی<select defaultValue="tehran"><option value="tehran">Asia/Tehran (UTC+۳:۳۰)</option></select></label><button className="primary">ذخیره تغییرات</button></section><section className="panel settings"><h2>امنیت و نشست</h2><p>کنترل دسترسی و ورود کاربران</p>{['تأیید دو مرحله‌ای','ثبت رخدادهای امنیتی','خروج خودکار'].map((x,i)=><div className="toggle-row" key={x}><span><b>{x}</b><small>{i===0?'برای مدیران الزامی باشد':i===1?'ذخیره تغییرات حساس در Audit Log':'پس از ۳۰ دقیقه عدم فعالیت'}</small></span><i className={i<2?'on':''}/></div>)}</section></div></>}
function PersonModal({person,canChange,onClose,onUpdate}:{person:Person;canChange:boolean;onClose:()=>void;onUpdate:(p:Person,s:Status,r:string|null)=>void}){const [status,setStatus]=useState(person.status),[reason,setReason]=useState('');const options=nextStatuses[person.status]??[];return <div className="backdrop"><div className="modal"><button className="x" onClick={onClose}><Icon name="close"/></button><small>جزئیات فرد · {person.id}</small><h2>{person.firstName} {person.lastName}</h2><div className="summary"><Avatar text={person.firstName[0]}/><span><b>{person.firstName} {person.lastName}</b><small>آخرین ثبت: {person.updatedAt} · {person.updatedBy}</small></span><Badge status={person.status}/></div><div className="details"><span>کد ملی<b>{person.nationalId}</b></span><span>تاریخ تولد<b>{person.birthDate}</b></span><span>نام پدر<b>{person.fatherName}</b></span><span>ثبت‌کننده<b>{person.updatedBy}</b></span></div><div className="stepper">{workflow.slice(0,9).map((s,i)=><span className={i<=workflow.indexOf(person.status)?'done':''} key={s}>{i+1}</span>)}</div>{canChange ? options.length?<label>مرحله بعدی<select value={status} onChange={e=>setStatus(e.target.value as Status)}><option value={person.status}>{person.status} (فعلی)</option>{options.map(s=><option key={s}>{s}</option>)}</select></label>:<div className="modal-note">این پرونده در وضعیت نهایی قرار دارد.</div> : <div className="modal-note">شما دسترسی تغییر وضعیت ندارید؛ این صفحه فقط برای مشاهده است.</div>}{canChange && status==='رد شده'&&<label>علت رد اجباری<textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder="علت رد پرونده را وارد کنید..."/></label>}<div className="modal-actions"><button className="outline" onClick={onClose}>بستن</button>{canChange&&<button className="primary" disabled={status===person.status||(status==='رد شده'&&!reason.trim())} onClick={()=>onUpdate(person,status,status==='رد شده'?reason:null)}><Icon name="check"/> ذخیره تغییرات</button>}</div></div></div>}
function CreateModal({existing,onClose,onCreate}:{existing:Person[];onClose:()=>void;onCreate:(p:Person)=>void}){const [firstName,setFirstName]=useState(''),[lastName,setLastName]=useState(''),[nationalId,setNationalId]=useState(''),[birthDate,setBirthDate]=useState(''),[fatherName,setFatherName]=useState(''),[error,setError]=useState('');const submit=(e:FormEvent)=>{e.preventDefault();const id=normalizeId(nationalId);if(!firstName.trim()||!lastName.trim()||!fatherName.trim()){setError('نام، نام خانوادگی و نام پدر الزامی هستند.');return}if(!validNationalId(id)){setError('کد ملی معتبر نیست.');return}if(existing.some(p=>normalizeId(p.nationalId)===id)){setError('این کد ملی قبلاً ثبت شده است.');return}if(birthDate&&!validBirthDate(birthDate)){setError('تاریخ تولد معتبر نیست.');return}onCreate({id:`P-${Date.now().toString().slice(-5)}`,firstName:firstName.trim(),lastName:lastName.trim(),nationalId:id,birthDate:birthDate||'—',fatherName:fatherName.trim(),status:'درخواست پرونده',updatedAt:'همین الان',updatedBy:'احمد محمدی'})};return <div className="backdrop"><form className="modal" onSubmit={submit}><button type="button" className="x" onClick={onClose}><Icon name="close"/></button><small>ثبت اطلاعات پایه</small><h2>افزودن فرد جدید</h2><p>فقط اطلاعات متنی ثبت می‌شود؛ هیچ فایل یا مدرکی در سامانه بارگذاری نمی‌شود.</p><div className="form-grid"><label>نام *<input required value={firstName} onChange={e=>setFirstName(e.target.value)}/></label><label>نام خانوادگی *<input required value={lastName} onChange={e=>setLastName(e.target.value)}/></label><label>کد ملی *<input required value={nationalId} onChange={e=>{setNationalId(e.target.value);setError('')}}/></label><label>تاریخ تولد<input value={birthDate} onChange={e=>setBirthDate(e.target.value)} placeholder="۱۳۷۸/۰۲/۱۲"/></label><label>نام پدر *<input required value={fatherName} onChange={e=>setFatherName(e.target.value)}/></label></div>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button type="button" className="outline" onClick={onClose}>انصراف</button><button className="primary"><Icon name="plus"/> ثبت فرد</button></div></form></div>}
